### ISSUE TITLE
Allways Error: value for items is missing

### ISSUE THREAD

**Issue by twine003** [capacitor-community/firebase-analytics#22]
Hi community.

I'm dealing with this issue, i don't know if i'm doing something wrong, but every time i call logEvent with "items" property i get an error saying "value for items is missing"

this is my implementation

```
FirebaseAnalytics.logEvent({
      name: "product_click", params: {
        content_type: "page_view",
        item_id: producto.id,
        item_name: producto.nombre,
        comerce_id: producto.comercio,
        source: "selections",
        items: [{
          tipo: "producto",
          nombre: producto.nombre,
          id: producto.id
        }],
      }
    });

```
i see the error occurs in FirebaseAnalytics.java line 149 since in mi implementation "Item" is not an String, Integer, Doble en so on.

```
while (keys.hasNext()) {
            String key = keys.next();
            Object value = params.get(key);

            if (value instanceof String) {
              bundle.putString(key, (String) value);
            } else if (value instanceof Integer) {
              bundle.putInt(key, (Integer) value);
            } else if (value instanceof Double) {
              bundle.putDouble(key, (Double) value);
            } else if (value instanceof Long) {
              bundle.putLong(key, (Long) value);
            } else {
              call.reject("value for " + key + " is missing");
            }
          }
```
I need help, thanks in advance.

**Comment by ausias-armesto** [comment]
Hi, 
It seems that @Mathyn has already solve this issue. I hope he creates a Pull request to the project so we can all get profit of it.
https://github.com/capacitor-community/firebase-analytics/compare/master...Mathyn:master

**Comment by Mathyn** [comment]
@ausias-armesto I did start working on trying to add support for arrays of objects however I did not test it enough and an iOS implementation is missing (unless iOS does already support objects).

**Comment by somq** [comment]
Hi there, any update on this one @priyankpat?

**Comment by yunusfillik** [comment]
Hi there, add JSONArray condition for e-commerce.
Go to FirebaseAnalytics.java;

    node_modules\@capacitor-community\firebase- 
    analytics\android\src\main\java\com\getcapacitor\community\firebaseanalytics\FirebaseAnalytics.java

After then add this imports.

    import org.json.JSONObject;
    import org.json.JSONArray;
    import java.util.ArrayList;

and find a **logEvent** function in FirebaseAnalytics.java
you should to add 1 more **if else** condition for **value instanceof JSONArray**.

this is my code

        while (keys.hasNext()) {
          String key = keys.next();
          Object value = params.get(key);
          if (value instanceof String) {
            bundle.putString(key, (String) value);
          } else if (value instanceof Integer) {
            bundle.putInt(key, (Integer) value);
          } else if (value instanceof Double) {
            bundle.putDouble(key, (Double) value);
          } else if (value instanceof Long) {
            bundle.putLong(key, (Long) value);
          } else if (value instanceof JSONArray) { //add this condition for items

            JSONArray items = (JSONArray) value;
            ArrayList itemBundleList = new ArrayList();

            for (int i = 0; i < items.length(); i++) {
              Bundle itemBundle = new Bundle();
              JSONObject itemParams = items.getJSONObject(i);
              Iterator<String> itemKeys = itemParams.keys();

              while (itemKeys.hasNext()) {
                String itemKey = itemKeys.next();
                Object itemValue = itemParams.get(itemKey);
                if (itemValue instanceof String) {
                  itemBundle.putString(itemKey, (String) itemValue);
                } else if (itemValue instanceof Integer) {
                  itemBundle.putInt(itemKey, (Integer) itemValue);
                } else if (itemValue instanceof Double) {
                  itemBundle.putDouble(itemKey, (Double) itemValue);
                } else if (itemValue instanceof Long) {
                  itemBundle.putLong(itemKey, (Long) itemValue);
                }
              }

              itemBundleList.add(itemBundle);
            }

            bundle.putParcelableArrayList(key, itemBundleList);
          } else {
            call.reject("value for " + key + " is missing");
          }
        }

![image](https://user-images.githubusercontent.com/44272836/107116624-a9953880-6885-11eb-80f4-9505a4554ccb.png)

You can check this docs for more information.

- https://firebase.google.com/docs/android/setup#available-libraries
   (android/app/build.gradle)
   implementation platform('com.google.firebase:firebase-bom:26.4.0')
   implementation 'com.google.firebase:firebase-analytics'

- https://developers.google.com/tag-manager/android/v5/enhanced-ecommerce
   You can check out of VIEW_ITEM or VIEW_ITEM_LIST for how can you send items/products with android bundle.

- Also you can check out of this docs for more information.
  https://developers.google.com/analytics/devguides/collection/ga4/ecommerce
  https://firebase.google.com/docs/analytics/measure-ecommerce#java

**Comment by brownoxford** [comment]
@yunusfillik this seems related to the issue we just were working on in IOS - is this still broken for you?

**Comment by sverdlov** [comment]
Hi. Still exists for 0.3.3.

```javascript
this.analyticsService.logEvent({
    name: FBEvents.VIEW_ITEM,
    params: {
        currency: product.price.currency,
        value: product.price.value,
        items: [ { id: product.id, title: product.title } ]
    }
});
```

![2021-06-23_10-50](https://user-images.githubusercontent.com/15052094/123058579-a2745e80-d411-11eb-9a3c-6fca303136c2.png)

**Comment by yunusfillik** [comment]
@brownoxford yes same same.
We fixed e-commerce(Items) issues with you for Android and Ios. 
Thank you so much.

**Comment by yunusfillik** [comment]
@sverdlov i don't know latest version. I'm using "@capacitor-community/firebase-analytics": "^0.2.0".
But you can fix it yourself with hard-coded changes.
Check this solution
https://github.com/capacitor-community/firebase-analytics/issues/22#issuecomment-774458867

**Comment by StErMi** [comment]
Hi there I can confirm that with the `"@capacitor-community/firebase-analytics": "^1.0.0"` I still have this issue but **only** for **Android**.

Every event that has `items` as a custom parameter won't track those items if I check out the Firebase Debug View.

Do you know how to fix it?

**Comment by StErMi** [comment]
> Hi, It seems that @Mathyn has already solve this issue. I hope he creates a Pull request to the project so we can all get profit of it. [master...Mathyn:master](https://github.com/capacitor-community/firebase-analytics/compare/master...Mathyn:master)

why isn't this code merged with the current project?

**Comment by gbkwiatt** [comment]
How is that still an issue ?

**Comment by dkiselew** [comment]
Guys, who can merge that pull request, please merge it
